version: '3.9'
services:
  
    keycloak:
      image: "jboss/keycloak"
      container_name: keycloak
      ports:
        - "8081:8080"
      environment:
        KEYCLOAK_USER : root
        KEYCLOAK_PASSWORD : password

      
